# Generated by Django 6.0.5 on 2026-08-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_daily_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_deduction_per_absent_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('punch_in', models.DateTimeField()),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ems.attendance')),
            ],
            options={
                'ordering': ['punch_in'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('punch_out__isnull', True)), fields=('attendance',), name='one_open_session_per_attendance')],
            },
        ),
    ]
