# Generated by Django 6.0.5 on 2026-08-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_or_create_users(apps, schema_editor):
    Employee = apps.get_model("ems", "Employee")
    User = apps.get_model("auth", "User")
    for employee in Employee.objects.filter(user__isnull=True):
        username = "employee-{}".format(employee.pk)
        user = User.objects.create(username=username, email="")
        user.set_unusable_password()
        user.save(update_fields=["password"])
        employee.user_id = user.pk
        employee.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_workschedule_attendancesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='one_open_session_per_attendance',
        ),
        migrations.RunPython(link_or_create_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('attendance',), name='one_session_per_attendance'),
        ),
    ]
